### PR TITLE
feat: allow passing null or undefined as response body

### PR DESCRIPTION
**Pull request by dirkluijk**
Fixes https://github.com/IanVS/vitest-fetch-mock/issues/25

### CODE REVIEW

**Comment by IanVS** [comment]
I can also construct a `Response` in Chrome using `new Response(undefined, {status: 204})`, should that also be allowed here?

**Comment by dirkluijk** [comment]
Good idea, fixed!

**Comment by IanVS** [comment]
Mind handling the conflict here, @dirkluijk, and then I will merge and release `0.4.1`?

**Comment by dirkluijk** [comment]
Fixed!

**Pull request merged**
